// Pure merge logic, isolated from any Tauri/host import so it can be unit
// tested without a working `invoke` bare-specifier resolution in vitest.
// loadSettings() (below) is the thin host-calling wrapper around it.

export interface SubtitleSettings {
  write: boolean;
  writeAutoGenerated: boolean;
  languages: string;
  embed: boolean;
}

export interface SponsorBlockSettings {
  mode: "off" | "mark" | "remove";
  categories: string[];
}

export interface YtDlpSettings {
  outputTemplate: string;
  format: string;
  downloadPlaylists: boolean;
  playlistItems: string;
  audioOnly: boolean;
  audioFormat: string;
  embedThumbnail: boolean;
  embedMetadata: boolean;
  embedChapters: boolean;
  subtitles: SubtitleSettings;
  sponsorBlock: SponsorBlockSettings;
  downloadArchiveEnabled: boolean;
  rateLimit: string;
  concurrentFragments: number;
  retries: number;
  sleepIntervalMinSeconds: number;
  sleepIntervalMaxSeconds: number;
  proxy: string;
  extraArgs: string[];
  autoUpdateCheckOnStartup: boolean;
}

export const DEFAULT_SETTINGS: YtDlpSettings = {
  outputTemplate: "%(title)s [%(id)s].%(ext)s",
  format: "bestvideo+bestaudio/best",
  downloadPlaylists: false,
  playlistItems: "",
  audioOnly: true,
  audioFormat: "mp3",
  embedThumbnail: true,
  embedMetadata: true,
  embedChapters: false,
  subtitles: {
    write: false,
    writeAutoGenerated: false,
    languages: "en.*",
    embed: true,
  },
  sponsorBlock: {
    mode: "off",
    categories: ["sponsor"],
  },
  downloadArchiveEnabled: false,
  rateLimit: "",
  concurrentFragments: 1,
  retries: 10,
  sleepIntervalMinSeconds: 5,
  sleepIntervalMaxSeconds: 25,
  proxy: "",
  extraArgs: [],
  autoUpdateCheckOnStartup: true,
};

// Shallow-merges a partially-shaped/older settings.json over the defaults so
// a manually-edited (or version-skewed) file never crashes the plugin.
// Nested objects (subtitles/sponsorBlock) get their own shallow merge too.
export function mergeSettings(defaults: YtDlpSettings, parsed: unknown): YtDlpSettings {
  if (!parsed || typeof parsed !== "object") return { ...defaults };
  const p = parsed as Partial<YtDlpSettings> & Record<string, unknown>;
  return {
    ...defaults,
    ...p,
    subtitles: { ...defaults.subtitles, ...(isObject(p.subtitles) ? p.subtitles : {}) },
    sponsorBlock: { ...defaults.sponsorBlock, ...(isObject(p.sponsorBlock) ? p.sponsorBlock : {}) },
  } as YtDlpSettings;
}

function isObject(v: unknown): v is Record<string, unknown> {
  return !!v && typeof v === "object" && !Array.isArray(v);
}

// Reads settings.json via the host's raw plugin-settings Tauri command
// (api.fs is sandboxed to this plugin's own data\ folder and can't reach
// settings.json, which lives one level up next to plugin.json).
export async function loadSettings(pluginId: string): Promise<YtDlpSettings> {
  const { invoke } = await import("@tauri-apps/api/core");
  try {
    const raw = await invoke<string>("read_plugin_settings_file", { dir: pluginId });
    const parsed = JSON.parse(raw);
    return mergeSettings(DEFAULT_SETTINGS, parsed);
  } catch {
    return { ...DEFAULT_SETTINGS };
  }
}
